apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server-wp
  name: server-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server-wp
    spec:
      containers:
        - image: wordpress
          name: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: server-bd
            - name: WORDPRESS_DB_USER
              value: user_wp
            - name: WORDPRESS_DB_PASSWORD
              value: admin
            - name: WORDPRESS_DB_NAME
              value: bd_wp
